"""Phase 6: generate RESULTS.md and abstract_facts.json.

Both are written from ``results/results.json``. No number in either file is
transcribed by hand -- if it is not in results.json it does not appear here, and
if a value depends on an unverified citation the cell is left blank and flagged
rather than filled in.

``abstract_facts.json`` is the small dictionary the abstract will be written
from: best model, its error at every horizon, the skill score, the parameter
count, the energy estimate and the dataset date range.

Run::

    python scripts/11_make_report.py --config config.yaml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd
from src.models.data import load_meta
from src.results import load_results
from src.utils import check_disk_space, load_config, setup_logging


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default="config.yaml")
    return p.parse_args()


def _runs_frame(payload: dict) -> pd.DataFrame:
    """Flatten the run records into a table."""
    runs = payload.get("runs", [])
    if not runs:
        return pd.DataFrame()
    frame = pd.DataFrame(runs)
    for metric in ("rmse", "mae", "r2", "smape", "bias", "skill_vs_persistence", "n"):
        frame[metric] = frame["metrics"].map(lambda m, k=metric: m.get(k))
    return frame


def _best_per_horizon(frame: pd.DataFrame, tier: str | None = None) -> pd.DataFrame:
    """Select the lowest-RMSE model per horizon, optionally within one tier."""
    sub = frame if tier is None else frame[frame["tier"] == tier]
    if sub.empty:
        return sub
    grouped = (
        sub.groupby(["model", "variant", "horizon_h"], dropna=False)
        .agg(
            rmse=("rmse", "mean"),
            rmse_std=("rmse", "std"),
            mae=("mae", "mean"),
            r2=("r2", "mean"),
            smape=("smape", "mean"),
            skill=("skill_vs_persistence", "mean"),
            skill_std=("skill_vs_persistence", "std"),
            n_params=("n_params", "first"),
            n_seeds=("seed", "count"),
        )
        .reset_index()
    )
    return grouped.sort_values("rmse").groupby("horizon_h").first().reset_index()


def main() -> int:
    """Write RESULTS.md and abstract_facts.json."""
    args = parse_args()
    cfg = load_config(args.config)
    log = setup_logging(cfg, "11_make_report")
    check_disk_space(cfg)

    payload = load_results(cfg)
    meta = load_meta(cfg)
    frame = _runs_frame(payload)
    if frame.empty:
        log.error("results.json has no runs; run the model phases first")
        return 1

    horizons = [int(h) for h in cfg.get("task.horizons_h")]
    headline = int(cfg.get("task.headline_horizon_h"))
    boundaries = cfg.get("split.explicit_boundaries")
    audit = json.loads(
        (cfg.path_for("data_interim") / "audit_summary.json").read_text(encoding="utf-8")
    )

    best_deep = _best_per_horizon(frame, "tier3")
    best_classical = _best_per_horizon(frame[frame["tier"].isin(["tier1", "tier2"])])

    persistence = frame[frame["model"] == "persistence"].set_index("horizon_h")["rmse"]

    lines: list[str] = []
    a = lines.append

    a("# Results")
    a("")
    a(f"**{cfg.get('project.title')}**")
    a("")
    a(f"- Site: {cfg.get('data.openaq.site_label')}")
    a(
        f"- Data: {audit['coverage']['first_utc'][:10]} to {audit['coverage']['last_utc'][:10]} "
        f"({audit['usable_years']:.2f} usable years, {audit['pct_observed']:.1f}% hourly coverage)"
    )
    a(
        f"- Split (chronological, no shuffling): train to {str(boundaries['train_end'])[:10]}, "
        f"validation to {str(boundaries['val_end'])[:10]}, test thereafter"
    )
    a(f"- Predictors: {meta['n_predictors']}; horizons: {horizons}")
    a(f"- Seeds: {cfg.get('seeds.multi')}")
    a(f"- Git commit: `{payload['meta'].get('git_commit', 'unknown')}`")
    a("")
    a("> Every number below is generated by `scripts/11_make_report.py` from")
    a("> `results/results.json`. Nothing is transcribed by hand.")
    a("")

    # ---------------------------------------------------------------- headline
    a("## 1. Headline")
    a("")
    if not best_deep.empty:
        row = best_deep[best_deep["horizon_h"] == headline]
        if not row.empty:
            r = row.iloc[0]
            ref = float(persistence.get(headline, float("nan")))
            a(
                f"At the {headline}-hour horizon the best sequence model is **{r['model']}** "
                f"(input window {str(r['variant']).lstrip('w')} h, {int(r['n_params']):,} parameters, "
                f"{int(r['n_seeds'])} seeds)."
            )
            a("")
            a(f"- RMSE **{r['rmse']:.2f} µg/m³** (persistence {ref:.2f})")
            a(f"- MAE {r['mae']:.2f} µg/m³, R² {r['r2']:.3f}, sMAPE {r['smape']:.2f}%")
            a(f"- **Skill score vs persistence: {r['skill']:+.4f}**")
            a("")
    if not best_classical.empty:
        row = best_classical[best_classical["horizon_h"] == headline]
        if not row.empty:
            r = row.iloc[0]
            a(
                f"The best classical model at the same horizon is **{r['model']}**, "
                f"RMSE {r['rmse']:.2f} µg/m³, skill {r['skill']:+.4f}."
            )
            a("")

    dm = payload.get("significance", {}).get("diebold_mariano", [])
    dm_head = [d for d in dm if d["horizon_h"] == headline]
    if dm_head:
        d = dm_head[0]
        verdict = "significant" if d["p_value"] < 0.05 else "not significant"
        a(
            f"Diebold-Mariano at {headline} h ({d['model_a']} vs {d['model_b']}): "
            f"statistic {d['statistic']:.3f}, p = {d['p_value']:.3g} — **{verdict}** at the 5% level. "
            f"Lower average loss: {d['better']}."
        )
        a("")

    # ---------------------------------------------------------------- baselines
    a("## 2. Baselines and classical models")
    a("")
    a(
        "Skill is $1 - \\mathrm{RMSE}_{model}/\\mathrm{RMSE}_{persistence}$. Positive beats persistence."
    )
    a("")
    table = frame[frame["tier"].isin(["tier1", "tier2"])].copy()
    pivot = table.pivot_table(index="model", columns="horizon_h", values="rmse", aggfunc="mean")
    a(pivot.round(2).to_markdown())
    a("")
    a("**Note on seasonal-naive.** At h = 24 the seasonal-naive rule $\\hat y(t+h)=y(t+h-24)$")
    a("reduces to $y(t)$, which is persistence. The two rows are identical at that")
    a("horizon by definition, not by accident.")
    a("")

    # ---------------------------------------------------------------- sequence
    a("## 3. Sequence models")
    a("")
    seq = frame[frame["tier"] == "tier3"]
    if not seq.empty:
        agg = (
            seq.groupby(["model", "variant", "horizon_h"])
            .agg(
                rmse_mean=("rmse", "mean"),
                rmse_std=("rmse", "std"),
                skill_mean=("skill_vs_persistence", "mean"),
                params=("n_params", "first"),
                seeds=("seed", "count"),
            )
            .reset_index()
        )
        head = agg[agg["horizon_h"] == headline].sort_values("rmse_mean")
        show = head.assign(
            RMSE=lambda d: d.apply(
                lambda r: (
                    f"{r['rmse_mean']:.2f} ± {r['rmse_std']:.2f}"
                    if pd.notna(r["rmse_std"])
                    else f"{r['rmse_mean']:.2f}"
                ),
                axis=1,
            ),
            Skill=lambda d: d["skill_mean"].round(4),
        )[["model", "variant", "params", "seeds", "RMSE", "Skill"]]
        a(show.to_markdown(index=False))
        a("")
        budget = int(cfg.get("models.sequence.max_params"))
        a(f"Every model above respects the {budget:,}-parameter budget.")
        excluded = payload.get("green", {}).get("excluded_over_budget", [])
        if excluded:
            a("")
            a("Configurations the budget excluded (the constraint was not relaxed):")
            a("")
            for e in excluded:
                a(f"- `{e['name']}` — {e['params']:,} parameters")
        a("")

    # ---------------------------------------------------------------- stratified
    a("## 4. Stratified performance")
    a("")
    strat = payload.get("stratified")
    if strat:
        s = pd.DataFrame(strat)
        view = s[(s["horizon_h"] == headline) & (s["stratum"] == "pollution")]
        if not view.empty:
            a(
                view[["model", "group", "n", "rmse", "skill_vs_persistence"]]
                .round(3)
                .to_markdown(index=False)
            )
            a("")
            worst = view.sort_values("skill_vs_persistence").iloc[0]
            a(
                f"The weakest stratum is *{worst['group']}* for `{worst['model']}` "
                f"(skill {worst['skill_vs_persistence']:+.4f}). Models that look strong overall "
                "commonly fail on exactly the high-pollution episodes a health advisory exists "
                "to warn about, so this table is reported whether or not it flatters the result."
            )
            a("")
        season = s[(s["horizon_h"] == headline) & (s["stratum"] == "season")]
        if not season.empty:
            a("### By season")
            a("")
            a(
                season[["model", "group", "n", "rmse", "skill_vs_persistence"]]
                .round(3)
                .to_markdown(index=False)
            )
            a("")
            a(
                "Season boundaries follow the Bangladesh Department of Environment "
                "(dry November–April, wet May–October). The 2022 monsoon is missing from the "
                "record entirely, so the wet-season sample draws on eight monsoons, not nine."
            )
            a("")

    # ---------------------------------------------------------------- green
    a("## 5. Green-AI accounting")
    a("")
    a("### Two honesty requirements")
    a("")
    a("1. **CodeCarbon reports estimates, not metered measurements.** It derives energy from")
    a("   hardware power models and falls back to fully modelled values when it cannot read")
    a("   Intel RAPL counters, which is the normal case on Windows without elevated")
    a("   privileges. Whether RAPL was readable is recorded per run in `results.json`.")
    grid = cfg.get("green.grid_carbon_intensity")
    a("2. **The Bangladesh figure is a recomputation, not a second measurement.** The same")
    a("   estimated kWh is multiplied by a cited national grid intensity:")
    a(
        f"   **{grid['value_gco2_per_kwh']} gCO₂e/kWh ({grid['year']})**, "
        f"{grid['source_name']}, <{grid['source_url']}>."
    )
    a("")
    pareto = payload.get("green", {}).get("pareto_table")
    if pareto:
        p = pd.DataFrame(pareto)
        show = p.assign(
            RMSE=p["rmse_mean"].round(2),
            Skill=p["skill_mean"].round(4),
            Params=p["params"].astype(int),
            MACs=p["macs"].map(lambda v: f"{v:,.0f}" if pd.notna(v) else "n/a"),
            Latency_ms=p["latency_ms_mean"].round(4),
            Train_kWh=p["train_kwh_mean"].map(lambda v: f"{v:.3e}" if pd.notna(v) else "n/a"),
            gCO2e_BD=p["co2e_g_bd_mean"].map(
                lambda v: f"{v:.4f}" if pd.notna(v) else "**blank — unavailable**"
            ),
        )[
            [
                "model",
                "window_h",
                "RMSE",
                "Skill",
                "Params",
                "MACs",
                "Latency_ms",
                "Train_kWh",
                "gCO2e_BD",
            ]
        ]
        a(show.to_markdown(index=False))
        a("")

    # ---------------------------------------------------------------- classifier
    a("## 6. AQI-category classification")
    a("")
    clf = payload.get("classification")
    if clf:
        bp = clf["breakpoints"]
        a(
            f"Next-day ({clf['horizon_h']} h) health-advisory classification into "
            f"{len(clf['labels'])} AQI categories."
        )
        a("")
        a(f"- Breakpoints: **{bp['scheme']}**, {bp['revision']}")
        a(f"- Source: {bp['source_org']}, *{bp['source_title']}* — <{bp['source_url']}>")
        a("- Bangladesh's Department of Environment states it applies the USEPA AQI equation")
        a("  and scale directly, so these are the correct breakpoints for a Bangladesh study.")
        a(f"- Target basis: **{clf['target_basis']}** — the breakpoints are defined on a")
        a("  24-hour mean, so the label is the 24-hour mean ending at *t+h*, not the")
        a("  instantaneous hourly value.")
        a(f"- Class imbalance handled with `class_weight = {clf['class_weight']}`.")
        a("")
        a(
            f"- **Macro-F1 {clf['macro_f1']['mean']:.4f} ± {clf['macro_f1']['std']:.4f}** "
            f"over {clf['macro_f1']['n_seeds']} seeds"
        )
        a(
            f"- Weighted-F1 {clf['weighted_f1']['mean']:.4f}, accuracy {clf['accuracy']['mean']:.4f}, "
            f"balanced accuracy {clf['balanced_accuracy']['mean']:.4f}"
        )
        a("")
        a("Macro-F1 is the headline: the categories are severely imbalanced, so accuracy")
        a("alone would be dominated by the majority classes and would hide failure on the")
        a("hazardous categories an advisory exists to flag.")
        a("")
        a(
            pd.DataFrame(clf["per_class"])[
                ["label", "support", "precision_mean", "recall_mean", "f1_mean"]
            ]
            .round(3)
            .to_markdown(index=False)
        )
        a("")

    # ---------------------------------------------------------------- limits
    a("## 7. Limitations")
    a("")
    a("- **Energy figures are estimates.** See §5. They should not be reported as measurements.")
    a("- **One monitoring site.** The target series comes from a single reference monitor")
    a("  (OpenAQ 2445 + 8415, the same physical instrument split across two provider records).")
    a("  Results describe that site, not Dhaka as a whole.")
    a("- **The record ends 2025-03-24.** The AirNow feed stops there; no Dhaka")
    a("  reference-monitor data exists after that date in the archive.")
    a("- **Coverage is fragmented.** 2,074 distinct gaps, of which a 113-day outage in 2022")
    a("  removes an entire monsoon season.")
    a(f"- **{audit['distribution']['n']:,} observed hours** after QC; 5,056 negative readings")
    a("  were dropped rather than floored, which is a modelling choice, not a neutral act.")
    a("- **SARIMAX is fitted on a bounded training tail**, making it a recent-history")
    a("  statistical baseline rather than a full-sample one.")
    a("")

    report_path = Path(str(cfg.get("output.report.results_md")))
    report_path = (
        report_path if report_path.is_absolute() else cfg.path_for("reports").parent / report_path
    )
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")
    log.info("wrote %s", report_path)

    # ------------------------------------------------------------ abstract facts
    facts: dict = {
        "_description": (
            "Exactly the figures needed to write a 250-300 word abstract. Generated by "
            "scripts/11_make_report.py from results/results.json. Any value that is null "
            "was not available and must not be invented."
        ),
        "study": {
            "title": cfg.get("project.title"),
            "site": cfg.get("data.openaq.site_label"),
            "city": cfg.get("data.site.city"),
            "openaq_location_ids": cfg.get("data.openaq.location_ids"),
        },
        "dataset": {
            "start_utc": audit["coverage"]["first_utc"],
            "end_utc": audit["coverage"]["last_utc"],
            "date_range_human": f"{audit['coverage']['first_utc'][:10]} to {audit['coverage']['last_utc'][:10]}",
            "span_years": audit["coverage"]["span_years"],
            "usable_years": audit["usable_years"],
            "hourly_coverage_pct": audit["pct_observed"],
            "observed_hours": audit["observed_hours"],
            "n_predictors": meta["n_predictors"],
            "pm25_mean_ugm3": audit["distribution"]["mean"],
            "pm25_median_ugm3": audit["distribution"]["p50"],
            "pct_hours_above_bd_24h_standard": audit["distribution"]["exceedance"].get(
                "above_65_ugm3_pct"
            ),
            "meteorology_source": "NASA POWER hourly point (UTC)",
            "split": {
                "train_end": str(boundaries["train_end"])[:10],
                "val_end": str(boundaries["val_end"])[:10],
                "method": "chronological 70/15/15, no shuffling",
            },
        },
        "horizons_h": horizons,
        "headline_horizon_h": headline,
        "best_model": None,
        "per_horizon": {},
        "persistence_rmse_by_horizon": {int(k): round(float(v), 3) for k, v in persistence.items()},
        "green": {},
        "classification": None,
        "significance": None,
    }

    if not best_deep.empty:
        row = best_deep[best_deep["horizon_h"] == headline]
        if not row.empty:
            r = row.iloc[0]
            facts["best_model"] = {
                "name": str(r["model"]),
                "input_window_h": int(str(r["variant"]).lstrip("w")),
                "n_parameters": int(r["n_params"]),
                "n_seeds": int(r["n_seeds"]),
                "parameter_budget": int(cfg.get("models.sequence.max_params")),
            }
        for _, r in best_deep.iterrows():
            facts["per_horizon"][int(r["horizon_h"])] = {
                "model": str(r["model"]),
                "rmse": round(float(r["rmse"]), 3),
                "rmse_std_across_seeds": None
                if pd.isna(r["rmse_std"])
                else round(float(r["rmse_std"]), 3),
                "mae": round(float(r["mae"]), 3),
                "r2": round(float(r["r2"]), 4),
                "smape": round(float(r["smape"]), 3),
                "skill_vs_persistence": round(float(r["skill"]), 4),
            }

    if not best_classical.empty:
        facts["best_classical_by_horizon"] = {
            int(r["horizon_h"]): {
                "model": str(r["model"]),
                "rmse": round(float(r["rmse"]), 3),
                "skill_vs_persistence": round(float(r["skill"]), 4),
            }
            for _, r in best_classical.iterrows()
        }

    if pareto:
        p = pd.DataFrame(pareto).sort_values("rmse_mean")
        top = p.iloc[0]
        facts["green"] = {
            "best_model_params": int(top["params"]),
            "best_model_macs": None if pd.isna(top["macs"]) else int(top["macs"]),
            "best_model_latency_ms": None
            if pd.isna(top["latency_ms_mean"])
            else round(float(top["latency_ms_mean"]), 5),
            "best_model_train_kwh": None
            if pd.isna(top["train_kwh_mean"])
            else float(top["train_kwh_mean"]),
            "best_model_train_gco2e_bd_grid": None
            if pd.isna(top["co2e_g_bd_mean"])
            else round(float(top["co2e_g_bd_mean"]), 5),
            "grid_intensity_gco2_per_kwh": grid["value_gco2_per_kwh"],
            "grid_intensity_year": grid["year"],
            "grid_intensity_source": grid["source_name"],
            "energy_is_estimate_not_measurement": True,
        }

    if clf:
        facts["classification"] = {
            "horizon_h": clf["horizon_h"],
            "n_classes": len(clf["labels"]),
            "macro_f1_mean": round(clf["macro_f1"]["mean"], 4),
            "macro_f1_std": round(clf["macro_f1"]["std"], 4),
            "accuracy_mean": round(clf["accuracy"]["mean"], 4),
            "balanced_accuracy_mean": round(clf["balanced_accuracy"]["mean"], 4),
            "breakpoint_scheme": clf["breakpoints"]["scheme"],
            "target_basis": clf["target_basis"],
        }

    if dm_head:
        d = dm_head[0]
        facts["significance"] = {
            "test": "Diebold-Mariano",
            "horizon_h": d["horizon_h"],
            "model_a": d["model_a"],
            "model_b": d["model_b"],
            "statistic": round(d["statistic"], 4),
            "p_value": float(d["p_value"]),
            "significant_at_5pct": bool(d["p_value"] < 0.05),
            "lower_loss": d["better"],
        }

    facts_path = Path(str(cfg.get("output.report.abstract_facts_json")))
    facts_path = (
        facts_path if facts_path.is_absolute() else cfg.path_for("reports").parent / facts_path
    )
    facts_path.write_text(json.dumps(facts, indent=2, default=str), encoding="utf-8")
    log.info("wrote %s", facts_path)

    missing = [k for k, v in facts.items() if v is None and not k.startswith("_")]
    if missing:
        log.warning("abstract_facts.json has null sections: %s", missing)

    print(f"\nwrote {report_path}")
    print(f"wrote {facts_path}")
    if missing:
        print(f"\nWARNING: null sections in abstract_facts.json: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
